INSERT INTO Office (OfficeID, Name, Location) VALUES ('1', 'Harris, Schneider and Horn', 'West Darlene');
INSERT INTO Office (OfficeID, Name, Location) VALUES ('2', 'Rodriguez-Ewing', 'Brucefurt');
INSERT INTO Office (OfficeID, Name, Location) VALUES ('3', 'Dunn Group', 'Hayneschester');
INSERT INTO Office (OfficeID, Name, Location) VALUES ('4', 'Espinoza-Cruz', 'West Jamesport');
INSERT INTO Office (OfficeID, Name, Location) VALUES ('5', 'Walker PLC', 'Amyland');
INSERT INTO Factory (FactoryID, Name, Location) VALUES ('1', 'Villarreal, Villarreal and Hamilton', 'Erinbury');
INSERT INTO Factory (FactoryID, Name, Location) VALUES ('2', 'Wilson and Sons', 'Elizabethtown');
INSERT INTO Factory (FactoryID, Name, Location) VALUES ('3', 'Morrow Inc', 'West Johnhaven');
INSERT INTO Factory (FactoryID, Name, Location) VALUES ('4', 'Martin-Hubbard', 'Millerburgh');
INSERT INTO Factory (FactoryID, Name, Location) VALUES ('5', 'Martin, Price and Sullivan', 'East Davidberg');
INSERT INTO Supplier (SupplierID, Name, Phone) VALUES ('1', 'Morrison, Kramer and Casey', '+1-545-539-1644');
INSERT INTO Supplier (SupplierID, Name, Phone) VALUES ('2', 'Ross LLC', '(860)563-2864');
INSERT INTO Supplier (SupplierID, Name, Phone) VALUES ('3', 'Johnson-Wilkins', '(060)007-9901');
INSERT INTO Supplier (SupplierID, Name, Phone) VALUES ('4', 'Bryant, Krueger and Mitchell', '618.994.8147x9096');
INSERT INTO Supplier (SupplierID, Name, Phone) VALUES ('5', 'Hall PLC', '459.594.1520x5872');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('1', 'No', '317', '3');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('2', 'Site', '134', '5');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('3', 'Security', '445', '5');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('4', 'Take', '124', '2');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('5', 'Stay', '367', '3');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('6', 'Focus', '159', '1');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('7', 'Fill', '246', '4');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('8', 'Serve', '134', '4');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('9', 'Evening', '481', '4');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('10', 'Billion', '479', '4');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('11', 'Turn', '479', '5');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('12', 'Cover', '102', '2');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('13', 'Subject', '211', '3');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('14', 'Practice', '101', '2');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('15', 'Raise', '485', '5');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('16', 'Thing', '313', '3');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('17', 'Whole', '192', '2');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('18', 'Experience', '405', '1');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('19', 'Feeling', '351', '1');
INSERT INTO RawMaterial (RawMaterialID, Name, Quantity, SupplierID) VALUES ('20', 'Many', '415', '3');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('1', 'Learn', '119', '65');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('2', 'Whatever', '159', '34');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('3', 'Trial', '162', '99');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('4', 'Green', '135', '100');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('5', 'Special', '74', '87');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('6', 'For', '181', '49');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('7', 'Sell', '116', '30');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('8', 'Particularly', '111', '96');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('9', 'School', '136', '52');
INSERT INTO Product (ProductID, Name, Price, Stock) VALUES ('10', 'Water', '194', '53');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('1', 'Timothy Spencer', 'fsingh@gmail.com', '430.266.0903x466');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('2', 'Andrew Ayala', 'devon56@gmail.com', '208.858.1915x3040');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('3', 'Eric Howell', 'martinlopez@coleman.com', '060.572.6394');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('4', 'Edward French', 'freemanmatthew@yahoo.com', '001-642-439-3525x846');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('5', 'James Morales', 'diane76@yahoo.com', '845-235-3278');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('6', 'Angie Jenkins', 'millerjordan@morgan-williamson.com', '611-215-5254x91032');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('7', 'Latasha Hawkins', 'ericksonscott@hotmail.com', '606-735-7526x375');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('8', 'Susan Thomas', 'ucollins@rogers.com', '+1-735-713-2422x397');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('9', 'Patrick Wilson', 'sclark@hotmail.com', '001-885-401-5765');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('10', 'Cassie Perez', 'brooksjohn@lawrence-russell.com', '+1-287-311-9347x47898');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('11', 'Nancy Clark', 'pgriffith@yahoo.com', '(386)328-8055');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('12', 'Brenda Alvarez', 'rileyanna@gmail.com', '001-823-024-1526x7028');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('13', 'Amber Green', 'jimmy85@williamson.info', '(215)876-6797');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('14', 'Julian Boyd', 'deniseperez@smith.com', '629.627.6558x15620');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('15', 'John Diaz', 'butlerbeverly@stewart-sanchez.org', '019.101.4573');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('16', 'Timothy Navarro', 'eduardoflowers@cannon.com', '316-982-4811');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('17', 'Erin Green', 'victoria91@yahoo.com', '974-590-1505');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('18', 'Kimberly Huff', 'amandafreeman@bird.com', '(704)391-8536');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('19', 'Daniel Hill', 'veronicazimmerman@lopez.net', '+1-239-968-5763');
INSERT INTO Customer (CustomerID, Name, Email, Phone) VALUES ('20', 'Angela Rice', 'vwatkins@hotmail.com', '(009)031-3432x4049');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('1', 'Gabrielle Lynch', '2665408406', '001-848-414-5711x699', 'kharris@gmail.com', '2024-01-13', '2551', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('2', 'Shelly Sanchez', '138784343', '787-490-7068', 'nathanorr@yahoo.com', '2023-03-29', '2415', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('3', 'Mark Nolan', '5294130146', '001-398-284-7822', 'gbarnett@ellis.com', '2023-12-23', '2346', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('4', 'Michelle Moreno', '6513727591', '638.911.4401x102', 'xwatkins@dalton.net', '2023-01-07', '3852', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('5', 'Derek Turner', '29749470', '001-511-772-4886x418', 'aaron29@yahoo.com', '2022-09-25', '3301', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('6', 'Christy Holt', '5697646942', '001-868-088-2391x1687', 'tgutierrez@jordan.com', '2022-11-17', '3386', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('7', 'Jennifer Rivera', '6040417538', '001-558-721-8040x299', 'williamswilliam@hotmail.com', '2023-03-19', '2661', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('8', 'Richard Vargas', '4824931370', '001-664-630-1831x7156', 'qhall@gmail.com', '2023-07-10', '1401', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('9', 'Thomas Garcia', '7900428286', '610-316-7219', 'natalie53@murphy.com', '2023-12-21', '3697', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('10', 'Monique Rivera', '8753659110', '+1-561-748-4624x542', 'lauren58@massey-hines.biz', '2022-07-02', '3147', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('11', 'Collin Johnson', '3848106887', '+1-965-314-8457', 'lisapage@vega.com', '2022-10-05', '3618', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('12', 'Rachel Clarke', '5001094071', '875.846.6000x8853', 'pateltyler@pittman.com', '2024-11-18', '1481', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('13', 'Joseph Graham', '4354046006', '001-096-138-4518x34334', 'gterry@yahoo.com', '2024-11-06', '1894', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('14', 'Amanda Flores', '8869578309', '+1-814-334-7556', 'carlsonstephen@gmail.com', '2022-09-07', '3127', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('15', 'Joel Moody', '7675470777', '572-986-6474', 'jmoore@gmail.com', '2023-06-19', '1434', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('16', 'Kimberly Flores', '6726989587', '+1-881-715-1295', 'andrewalvarez@yahoo.com', '2025-02-05', '2836', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('17', 'Nicole White', '8039796133', '001-621-312-0203x9125', 'arielthomas@gmail.com', '2023-07-02', '1618', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('18', 'Trevor Brown', '7164483338', '+1-236-872-0272x394', 'allisonmeyer@juarez.com', '2023-08-25', '3925', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('19', 'Ian Berg', '9991691274', '150-496-3164', 'taylormichael@yahoo.com', '2022-12-05', '3294', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('20', 'Adam Ruiz', '5470689995', '(329)489-7979', 'ewingtimothy@yahoo.com', '2023-05-27', '1367', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('21', 'Evelyn Coleman', '4486417074', '7339815989', 'gfritz@yahoo.com', '2025-05-12', '3301', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('22', 'Charles Long', '6234328171', '082-765-2016x85022', 'michellemoore@boyle.com', '2024-11-05', '2907', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('23', 'Lisa Moss', '6440375197', '128-734-0461x0410', 'wlee@yahoo.com', '2022-11-18', '2786', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('24', 'Ricky Wallace', '3241985475', '339-085-6022', 'garrettphillips@hotmail.com', '2023-05-31', '2668', 'OfficeEmployee');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('25', 'Jessica Lane MD', '408508043', '9826904389', 'mitchellerika@fernandez.com', '2023-02-19', '1482', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('26', 'Vicki Huffman', '5417827696', '+1-993-946-2138x924', 'noahclark@hotmail.com', '2024-04-09', '1412', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('27', 'Juan Edwards', '1229111722', '+1-068-580-3347x88231', 'amorris@gmail.com', '2023-04-14', '2721', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('28', 'Maria Moon', '1513941179', '+1-618-918-7863x93395', 'ralphgutierrez@knight.org', '2025-03-16', '1475', 'Worker');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('29', 'Robert Jones', '2313743901', '001-784-158-8013x1347', 'mayschristopher@gmail.com', '2023-10-01', '3162', 'Manager');
INSERT INTO Employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('30', 'Kevin Bradshaw', '6065320967', '255-401-4445x421', 'hartwilliam@yahoo.com', '2023-04-20', '2565', 'OfficeEmployee');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('3', 'A', 'Office', '4');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('5', 'C', 'Office', '5');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('8', 'C', 'Office', '3');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('10', 'A', 'Factory', '1');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('15', 'B', 'Factory', '1');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('17', 'A', 'Office', '2');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('21', 'C', 'Factory', '1');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('25', 'B', 'Office', '4');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('26', 'B', 'Factory', '1');
INSERT INTO Manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('29', 'C', 'Factory', '1');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('1', '2', 'Evening', 'yeah', '1');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('4', '1', 'Morning', 'piece', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('12', '4', 'Morning', 'shoulder', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('16', '5', 'Night', 'moment', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('19', '2', 'Night', 'follow', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('20', '2', 'Evening', 'find', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('22', '4', 'Evening', 'task', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('23', '1', 'Night', 'Congress', '0');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('27', '2', 'Night', 'lot', '1');
INSERT INTO Worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('28', '4', 'Evening', 'treatment', '1');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('2', '4', 'IT sales professional', 'interview');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('6', '4', 'Arboriculturist', 'start');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('7', '1', 'Technical brewer', 'price');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('9', '4', 'Music therapist', 'woman');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('11', '3', 'Location manager', 'gun');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('13', '3', 'Scientist, research (life sciences)', 'who');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('14', '5', 'Social researcher', 'me');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('18', '2', 'Financial controller', 'three');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('24', '1', 'Teacher, adult education', 'reduce');
INSERT INTO OfficeEmployee (EmployeeID, OfficeID, Role, Department) VALUES ('30', '3', 'Retail manager', 'simply');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('1', '17', '87');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('5', '1', '39');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '17', '11');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '9', '17');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('1', '20', '81');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('1', '13', '52');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '14', '81');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '14', '82');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '20', '82');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '12', '39');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '20', '72');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '10', '100');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '2', '75');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '8', '43');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '9', '32');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '9', '54');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('5', '7', '74');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '14', '65');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('1', '19', '37');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('3', '7', '20');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('3', '2', '24');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '14', '50');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('1', '16', '30');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('1', '19', '68');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '16', '84');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('3', '1', '26');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('3', '13', '58');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('2', '9', '47');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('4', '3', '59');
INSERT INTO FactoryRawMaterial (FactoryID, RawMaterialID, QuantityUsed) VALUES ('3', '1', '25');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('1', '7', '8', '2');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('2', '2', '3', '4');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('3', '18', '9', '3');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('4', '6', '2', '8');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('5', '8', '10', '9');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('6', '1', '10', '3');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('7', '6', '4', '4');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('8', '6', '7', '8');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('9', '18', '4', '4');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('10', '11', '2', '10');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('11', '6', '6', '8');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('12', '17', '1', '4');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('13', '11', '8', '7');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('14', '15', '8', '8');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('15', '1', '9', '7');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('16', '12', '9', '4');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('17', '9', '6', '1');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('18', '16', '10', '2');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('19', '4', '1', '1');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('20', '6', '6', '3');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('21', '15', '4', '5');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('22', '1', '6', '8');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('23', '8', '5', '2');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('24', '3', '5', '10');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('25', '10', '10', '10');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('26', '19', '8', '6');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('27', '16', '5', '3');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('28', '5', '7', '8');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('29', '2', '5', '10');
INSERT INTO OrderProduct (OrderID, CustomerID, ProductID, Quantity) VALUES ('30', '20', '6', '3');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('1', '7', '2025-01-29', '303');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('2', '2', '2024-06-03', '496');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('3', '18', '2024-12-22', '181');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('4', '6', '2024-09-30', '135');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('5', '8', '2025-03-05', '432');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('6', '1', '2024-07-19', '181');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('7', '6', '2024-06-07', '196');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('8', '6', '2024-11-01', '251');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('9', '18', '2025-01-29', '104');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('10', '11', '2024-09-08', '159');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('11', '6', '2024-12-27', '354');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('12', '17', '2024-10-01', '153');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('13', '11', '2024-06-10', '325');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('14', '15', '2024-06-07', '407');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('15', '1', '2024-08-01', '197');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('16', '12', '2024-10-09', '154');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('17', '9', '2025-04-12', '457');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('18', '16', '2024-06-18', '432');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('19', '4', '2024-09-26', '437');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('20', '6', '2024-10-31', '104');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('21', '15', '2024-06-12', '440');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('22', '1', '2025-02-11', '219');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('23', '8', '2025-04-16', '232');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('24', '3', '2024-10-03', '395');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('25', '10', '2024-11-27', '105');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('26', '19', '2024-07-12', '227');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('27', '16', '2025-01-08', '405');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('28', '5', '2024-08-02', '492');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('29', '2', '2025-03-08', '296');
INSERT INTO Transaction (TransactionID, CustomerID, Date, Amount) VALUES ('30', '20', '2025-04-30', '337');