INSERT INTO office (OfficeID, Name, Location, Phone, Email, ManagerID) VALUES ('1', 'Peterson Ltd', 'New Jason', '236-568-3812x743', 'normawilson@ortiz.info', '5');
INSERT INTO office (OfficeID, Name, Location, Phone, Email, ManagerID) VALUES ('2', 'Wang-Smith', 'Allenchester', '+1-615-743-9858x4051', 'lori75@cain.net', '1');
INSERT INTO office (OfficeID, Name, Location, Phone, Email, ManagerID) VALUES ('3', 'Weber PLC', 'Patrickburgh', '(365)633-7164', 'samuelroberts@jimenez.com', '3');
INSERT INTO office (OfficeID, Name, Location, Phone, Email, ManagerID) VALUES ('4', 'Stewart Ltd', 'Osborneshire', '001-808-773-7712x6113', 'gwyatt@brown.net', '3');
INSERT INTO office (OfficeID, Name, Location, Phone, Email, ManagerID) VALUES ('5', 'Evans, Carter and Smith', 'South Mark', '7826391735', 'wyattcharles@gmail.com', '2');
INSERT INTO factory (FactoryID, Name, Location, Phone, Email, EstablishedDate, Status, OfficeID, ManagerID) VALUES ('1', 'Villarreal, Villarreal and Hamilton', 'Erinbury');
INSERT INTO factory (FactoryID, Name, Location, Phone, Email, EstablishedDate, Status, OfficeID, ManagerID) VALUES ('2', 'Wilson and Sons', 'Elizabethtown');
INSERT INTO factory (FactoryID, Name, Location, Phone, Email, EstablishedDate, Status, OfficeID, ManagerID) VALUES ('3', 'Morrow Inc', 'West Johnhaven');
INSERT INTO factory (FactoryID, Name, Location, Phone, Email, EstablishedDate, Status, OfficeID, ManagerID) VALUES ('4', 'Martin-Hubbard', 'Millerburgh');
INSERT INTO factory (FactoryID, Name, Location, Phone, Email, EstablishedDate, Status, OfficeID, ManagerID) VALUES ('5', 'Martin, Price and Sullivan', 'East Davidberg');
INSERT INTO supplier (SupplierID, Name, CompanyName, Phone, Email, Location) VALUES ('1', 'Morrison, Kramer and Casey', '+1-545-539-1644');
INSERT INTO supplier (SupplierID, Name, CompanyName, Phone, Email, Location) VALUES ('2', 'Ross LLC', '(860)563-2864');
INSERT INTO supplier (SupplierID, Name, CompanyName, Phone, Email, Location) VALUES ('3', 'Johnson-Wilkins', '(060)007-9901');
INSERT INTO supplier (SupplierID, Name, CompanyName, Phone, Email, Location) VALUES ('4', 'Bryant, Krueger and Mitchell', '618.994.8147x9096');
INSERT INTO supplier (SupplierID, Name, CompanyName, Phone, Email, Location) VALUES ('5', 'Hall PLC', '459.594.1520x5872');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('1', 'No', '317', '3');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('2', 'Site', '134', '5');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('3', 'Security', '445', '5');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('4', 'Take', '124', '2');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('5', 'Stay', '367', '3');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('6', 'Focus', '159', '1');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('7', 'Fill', '246', '4');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('8', 'Serve', '134', '4');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('9', 'Evening', '481', '4');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('10', 'Billion', '479', '4');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('11', 'Turn', '479', '5');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('12', 'Cover', '102', '2');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('13', 'Subject', '211', '3');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('14', 'Practice', '101', '2');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('15', 'Raise', '485', '5');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('16', 'Thing', '313', '3');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('17', 'Whole', '192', '2');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('18', 'Experience', '405', '1');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('19', 'Feeling', '351', '1');
INSERT INTO rawmaterial (RawMaterialID, Name, Unit, CostPerUnit, StockQuantity, SupplierID) VALUES ('20', 'Many', '415', '3');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('1', 'Learn', '119', '65');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('2', 'Whatever', '159', '34');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('3', 'Trial', '162', '99');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('4', 'Green', '135', '100');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('5', 'Special', '74', '87');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('6', 'For', '181', '49');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('7', 'Sell', '116', '30');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('8', 'Particularly', '111', '96');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('9', 'School', '136', '52');
INSERT INTO product (ProductID, FactoryID, Name, Category, UnitPrice, StockQuantity, ProductionDate, ExpirationDate) VALUES ('10', 'Water', '194', '53');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('1', 'Timothy Spencer', 'fsingh@gmail.com', '430.266.0903x466');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('2', 'Andrew Ayala', 'devon56@gmail.com', '208.858.1915x3040');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('3', 'Eric Howell', 'martinlopez@coleman.com', '060.572.6394');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('4', 'Edward French', 'freemanmatthew@yahoo.com', '001-642-439-3525x846');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('5', 'James Morales', 'diane76@yahoo.com', '845-235-3278');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('6', 'Angie Jenkins', 'millerjordan@morgan-williamson.com', '611-215-5254x91032');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('7', 'Latasha Hawkins', 'ericksonscott@hotmail.com', '606-735-7526x375');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('8', 'Susan Thomas', 'ucollins@rogers.com', '+1-735-713-2422x397');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('9', 'Patrick Wilson', 'sclark@hotmail.com', '001-885-401-5765');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('10', 'Cassie Perez', 'brooksjohn@lawrence-russell.com', '+1-287-311-9347x47898');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('11', 'Nancy Clark', 'pgriffith@yahoo.com', '(386)328-8055');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('12', 'Brenda Alvarez', 'rileyanna@gmail.com', '001-823-024-1526x7028');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('13', 'Amber Green', 'jimmy85@williamson.info', '(215)876-6797');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('14', 'Julian Boyd', 'deniseperez@smith.com', '629.627.6558x15620');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('15', 'John Diaz', 'butlerbeverly@stewart-sanchez.org', '019.101.4573');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('16', 'Timothy Navarro', 'eduardoflowers@cannon.com', '316-982-4811');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('17', 'Erin Green', 'victoria91@yahoo.com', '974-590-1505');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('18', 'Kimberly Huff', 'amandafreeman@bird.com', '(704)391-8536');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('19', 'Daniel Hill', 'veronicazimmerman@lopez.net', '+1-239-968-5763');
INSERT INTO customer (CustomerID, FullName, Phone, Email, Address, RegisteredDate) VALUES ('20', 'Angela Rice', 'vwatkins@hotmail.com', '(009)031-3432x4049');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('1', 'Brian Nelson', '2241022824', '6460009152', 'toddsmith@taylor-smith.net', '2017-02-24', '4973.97', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('2', 'Jill Lee', '7064251478', '(501)829-5145', 'kimanna@gonzalez.com', '2022-09-11', '5004.85', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('3', 'Elizabeth Saunders', '959975379', '(720)579-3817x9700', 'obarker@williams.org', '2019-10-28', '4348.26', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('4', 'Vicki Hill', '3098865038', '212.830.3583x1170', 'wblankenship@yahoo.com', '2016-04-05', '5856.69', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('5', 'Wendy Gould', '8658474477', '096-515-3006x0316', 'briannahall@lopez-howard.com', '2023-07-24', '3331.54', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('6', 'Walter Carter', '1053981850', '769-081-2038x2083', 'ryan01@griffith.com', '2022-10-20', '4621.05', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('7', 'John Wilkins', '9022270387', '(340)433-0837', 'xgreen@gmail.com', '2017-09-02', '5025.95', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('8', 'Melissa Stevens', '1462277050', '656.644.9594x5359', 'usims@mason.com', '2023-09-19', '3413.51', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('9', 'Trevor Washington', '878050359', '001-775-035-7115x92820', 'wooddouglas@mitchell-bell.com', '2022-11-25', '1831.12', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('10', 'Tammy Smith', '7121192779', '980.278.6557x40925', 'woodstonya@gmail.com', '2023-09-20', '4308.44', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('11', 'John Peters', '9462140531', '633-917-4428x38236', 'dlopez@yahoo.com', '2020-12-31', '5954.46', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('12', 'Paul Daugherty', '9340981714', '919.131.2825', 'samantha12@conner-morrison.com', '2024-01-08', '4415.27', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('13', 'Brandon Diaz', '3195881138', '8964511583', 'daniel91@colon.com', '2015-10-24', '5494.76', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('14', 'Walter Delgado', '684104427', '6702284305', 'shepherdscott@bass.org', '2022-08-31', '2838.12', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('15', 'Tanya Walker', '6118131313', '+1-208-201-0820', 'mitchellmary@yahoo.com', '2017-12-17', '4579.58', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('16', 'Roberto Warner', '7921726937', '107-799-2944x61015', 'frederickdawn@miller.com', '2017-05-31', '3351.73', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('17', 'Angela Peters', '9074559784', '880-579-5556', 'isaacwelch@hardy.com', '2016-04-07', '2338.96', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('18', 'Gregory Franklin', '7402199975', '001-385-771-1282x6041', 'kmcintyre@davis.org', '2019-02-26', '3009.56', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('19', 'Taylor Perez', '4409347956', '404.875.6265x2379', 'hwagner@hotmail.com', '2017-05-13', '3083.81', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('20', 'Roy Sellers', '1844471592', '+1-329-658-5262x96359', 'sross@hotmail.com', '2015-12-28', '2610.77', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('21', 'Jacob Sweeney', '3494959874', '(739)484-8951x9399', 'nicolejones@mendoza-mccoy.net', '2021-09-04', '5730.65', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('22', 'Benjamin Russo', '5473766608', '164-979-1958x362', 'collinmorales@hotmail.com', '2016-10-21', '5029.78', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('23', 'Terri Osborne', '6613368135', '001-279-985-2025', 'tammy81@andrews-walker.com', '2020-05-04', '1949.52', 'Manager');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('24', 'Ian Gibbs', '4280322194', '(793)460-2135x843', 'holmeserin@kennedy.com', '2022-04-10', '5775.46', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('25', 'Lauren Phillips', '5360527668', '589-504-7050', 'elizabethcobb@hotmail.com', '2018-08-23', '5542.33', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('26', 'Maria Young', '5291219708', '097.270.5808x29365', 'gwest@gmail.com', '2019-07-16', '3713.01', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('27', 'Brandon Moore', '2488780676', '015.380.0034x3584', 'xbarajas@cruz.com', '2022-11-11', '1795.33', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('28', 'Dylan Gonzalez', '6412861263', '+1-268-355-1967x98630', 'lisawalsh@guzman.com', '2023-09-13', '4445.55', 'Worker');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('29', 'Justin Harris', '9598478215', '001-876-368-6360x6365', 'randypope@gmail.com', '2015-08-23', '4596.05', 'OfficeEmployee');
INSERT INTO employee (EmployeeID, Name, NationalID, Phone, Email, HireDate, Salary, Type) VALUES ('30', 'Thomas Watson', '8974598559', '001-716-664-5164x598', 'mossbarry@hotmail.com', '2017-03-21', '4197.41', 'OfficeEmployee');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('2', 'B', 'Factory', '4');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('3', 'B', 'Office', '1');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('6', 'C', 'Office', '2');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('12', 'B', 'Factory', '2');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('13', 'C', 'Factory', '2');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('14', 'C', 'Office', '1');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('16', 'C', 'Office', '2');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('18', 'C', 'Office', '4');
INSERT INTO manager (EmployeeID, Level, ManagesEntityType, ManagesEntityID) VALUES ('23', 'A', 'Office', '1');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('1', '1', 'Night', 'add', '1');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('7', '2', 'Morning', 'carry', '1');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('9', '2', 'Evening', 'technology', '0');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('10', '1', 'Night', 'design', '0');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('20', '3', 'Evening', 'and', '0');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('21', '2', 'Night', 'far', '0');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('22', '5', 'Morning', 'hard', '0');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('27', '5', 'Night', 'notice', '0');
INSERT INTO worker (EmployeeID, FactoryID, Shift, Skills, IsFullTime) VALUES ('28', '2', 'Morning', 'response', '0');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('4', '1', 'Field seismologist', 'worry');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('5', '1', 'Scientist, biomedical', 'what');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('8', '5', 'IT sales professional', 'network');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('11', '2', 'Restaurant manager, fast food', 'ability');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('15', '1', 'Therapist, occupational', 'face');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('17', '5', 'Purchasing manager', 'into');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('19', '2', 'Orthoptist', 'pretty');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('24', '1', 'Chiropodist', 'standard');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('25', '5', 'Education officer, environmental', 'hand');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('26', '4', 'Community arts worker', 'quickly');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('29', '4', 'Print production planner', 'hold');
INSERT INTO officeemployee (EmployeeID, OfficeID, Role, Department) VALUES ('30', '5', 'Community education officer', 'inside');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('1', '5', '2', '2024-06-17', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('2', '18', '1', '2024-10-20', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('3', '8', '4', '2024-05-14', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('4', '4', '2', '2025-05-04', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('5', '10', '4', '2024-05-21', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('6', '10', '4', '2023-12-14', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('7', '14', '4', '2024-03-13', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('8', '9', '5', '2025-04-06', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('9', '5', '5', '2025-03-15', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('10', '3', '2', '2025-04-14', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('11', '10', '2', '2024-06-25', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('12', '4', '2', '2024-11-28', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('13', '7', '3', '2024-12-04', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('14', '5', '1', '2023-07-16', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('15', '8', '5', '2025-02-26', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('16', '17', '3', '2024-11-29', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('17', '6', '1', '2024-04-29', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('18', '13', '1', '2024-12-11', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('19', '12', '4', '2024-03-29', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('20', '4', '2', '2025-01-15', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('21', '16', '5', '2024-02-05', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('22', '13', '1', '2024-04-19', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('23', '13', '1', '2025-01-01', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('24', '20', '5', '2025-05-03', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('25', '15', '3', '2024-11-24', 'Completed');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('26', '7', '3', '2024-08-02', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('27', '20', '5', '2025-04-26', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('28', '18', '4', '2024-08-16', 'Cancelled');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('29', '1', '3', '2023-12-29', 'Pending');
INSERT INTO order (OrderID, CustomerID, OfficeID, OrderDate, Status) VALUES ('30', '8', '4', '2025-03-01', 'Completed');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('1', '10', '2', '78.01');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('2', '4', '3', '21.14');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('2', '5', '2', '19.9');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('2', '8', '5', '43.25');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('3', '3', '5', '70.83');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('3', '2', '4', '60.15');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('3', '4', '3', '70.3');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('4', '6', '4', '36.86');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('4', '9', '1', '10.08');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('4', '6', '1', '44.31');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('5', '2', '1', '22.36');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('5', '5', '4', '64.54');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('5', '3', '1', '16.06');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('6', '2', '1', '58.01');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('6', '8', '3', '70.77');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('6', '3', '2', '34.11');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('7', '4', '3', '82.84');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('7', '2', '1', '82.01');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('7', '9', '3', '70.71');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('8', '2', '1', '10.99');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('8', '8', '3', '38.94');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('8', '9', '3', '41.17');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('9', '9', '4', '84.1');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('10', '8', '5', '59.88');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('11', '8', '4', '91.36');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('11', '3', '4', '52.54');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('11', '6', '5', '10.6');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('12', '1', '4', '29.56');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('13', '1', '3', '39.41');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('13', '7', '4', '69.19');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('14', '10', '3', '26.91');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('14', '4', '2', '42.98');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('14', '2', '1', '11.85');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('15', '5', '3', '92.42');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('16', '1', '4', '75.53');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('17', '1', '3', '28.23');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('18', '6', '4', '52.95');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('19', '8', '5', '58.82');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('19', '7', '5', '71.05');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('20', '10', '3', '69.92');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('20', '5', '5', '10.81');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('20', '7', '3', '11.46');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('21', '5', '3', '27.16');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('22', '9', '3', '74.11');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('22', '5', '3', '15.55');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('22', '8', '3', '70.78');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('23', '6', '5', '65.46');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('23', '8', '4', '58.16');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('23', '5', '4', '39.67');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('24', '1', '3', '32.28');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('24', '7', '2', '23.41');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('24', '10', '3', '62.33');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('25', '8', '3', '93.04');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('26', '5', '4', '90.62');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('26', '8', '3', '97.33');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('27', '3', '4', '62.88');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('28', '10', '1', '81.25');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('28', '6', '4', '56.95');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('29', '3', '5', '68.96');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('29', '7', '3', '16.24');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('30', '9', '5', '13.06');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('30', '3', '4', '13.84');
INSERT INTO orderproduct (OrderID, ProductID, Quantity, UnitPriceAtTime) VALUES ('30', '4', '4', '97.4');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('1', '1', '2024-10-30', '437.49', 'Card', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('2', '2', '2025-05-02', '72.19', 'Card', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('3', '3', '2024-05-19', '61.24', 'Cash', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('4', '4', '2025-05-12', '88.99', 'Card', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('5', '5', '2025-01-13', '72.6', 'Card', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('6', '6', '2024-10-26', '470.56', 'Card', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('7', '7', '2024-11-04', '198.77', 'Card', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('8', '8', '2025-04-24', '454.08', 'Cash', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('9', '9', '2025-05-01', '444.05', 'Cash', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('10', '10', '2025-05-01', '473.49', 'Online', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('11', '11', '2025-03-30', '338.59', 'Card', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('12', '12', '2025-02-22', '92.25', 'Online', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('13', '13', '2025-04-12', '172.93', 'Cash', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('14', '14', '2024-09-23', '120.87', 'Cash', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('15', '15', '2025-03-31', '379.39', 'Online', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('16', '16', '2025-01-11', '180.5', 'Card', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('17', '17', '2025-03-09', '361.13', 'Cash', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('18', '18', '2025-04-04', '403.93', 'Card', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('19', '19', '2024-09-21', '345.66', 'Cash', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('20', '20', '2025-01-15', '253.35', 'Card', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('21', '21', '2024-05-01', '438.43', 'Cash', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('22', '22', '2024-09-30', '275.07', 'Card', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('23', '23', '2025-02-23', '294.27', 'Card', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('24', '24', '2025-05-11', '94.17', 'Card', 'Success');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('25', '25', '2025-02-20', '259.04', 'Card', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('26', '26', '2025-04-05', '226.21', 'Cash', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('27', '27', '2025-05-06', '166.53', 'Online', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('28', '28', '2025-04-02', '313.65', 'Cash', 'Refunded');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('29', '29', '2024-07-17', '246.02', 'Cash', 'Failed');
INSERT INTO transaction (TransactionID, OrderID, PaymentDate, AmountPaid, Method, Status) VALUES ('30', '30', '2025-05-03', '422.18', 'Card', 'Refunded');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('2', '9', '59', '2024-09-06');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('3', '18', '43', '2024-10-02');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('3', '12', '16', '2024-12-10');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '9', '76', '2024-10-03');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '11', '94', '2024-06-29');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '7', '67', '2024-05-17');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '2', '86', '2025-04-22');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('4', '16', '69', '2025-02-21');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '3', '12', '2024-06-07');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('2', '7', '21', '2024-09-28');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('3', '5', '61', '2025-01-03');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('3', '20', '45', '2025-01-03');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '12', '97', '2024-08-05');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '2', '30', '2025-02-08');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('4', '18', '31', '2025-05-07');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('4', '8', '37', '2024-07-03');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '5', '39', '2024-10-24');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('2', '3', '68', '2024-10-01');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('4', '13', '97', '2024-10-13');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '12', '37', '2024-12-19');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '5', '89', '2024-07-22');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '2', '20', '2024-08-04');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '7', '30', '2024-08-19');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '5', '62', '2024-06-09');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '7', '100', '2024-12-17');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('4', '19', '14', '2024-12-13');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('2', '9', '18', '2024-10-06');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '9', '39', '2024-10-13');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('1', '19', '35', '2024-11-19');
INSERT INTO factoryrawmaterial (FactoryID, RawMaterialID, QuantityUsed, DateUsed) VALUES ('5', '3', '50', '2024-12-02');